apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-api-ingress
  namespace: phi-apps
  annotations:
    # Using ALB
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # Security (High-Compliance: TLS 1.2+)
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.alb.certificateArn }}" # Замените на ваш ARN

    # Automatic redirect to HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

    # Logging (High-Compliance: Audit traffic),
    # We use a bucket that has already been created in the S3/VPC module.
    alb.ingress.kubernetes.io/load-balancer-attributes: "access_logs.s3.enabled=true,access_logs.s3.bucket={{ .Values.alb.logBucketName }},access_logs.s3.prefix=alb-logs"

    # Protection (WAF v2)
    # Pre-Create a Web ACL in the AWS WAF Console
    alb.ingress.kubernetes.io/wafv2-acl-arn: "{{ .Values.alb.wafAclArn }}"

    # Health Checks (Production Ready)
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/success-codes: '200'

spec:
  rules:
    - host: "{{ .Values.domainName }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080