apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "platform-app.fullname" . }}-policy
spec:
  podSelector:
    matchLabels:
      {{ include "platform-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Limiting incoming traffic to port 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
  # Allow DNS requests (TCP/UDP 53)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
# Allowing access to AWS API and external services via HTTPS (443)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    - ports:
        - protocol: TCP
          port: 5432