{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.secretProviderClassName | default (include "platform-app.fullname" .) }}
  labels:
    {{ include "platform-app.labels" . | nindent 4 }}
spec:
  provider: aws
  {{- /*
The secretObjects section allows the driver to create standard Kubernetes Secrets based on data from AWS Secrets Manager.
This is the standard for production environments.
  */}}
  {{- if .Values.secrets.secretObjects }}
  secretObjects:
    {{- toYaml .Values.secrets.secretObjects | nindent 4 }}
  {{- end }}
  parameters:
    {{- /*
       Поле objects описывает, какие именно секреты забирать из внешнего хранилища.
    */}}
    objects: |
      {{- range .Values.secrets.objects -}}
      - objectName: {{ .objectName | quote }}
        objectType: {{ .objectType | default "secretsmanager" | quote }}
        {{- if .objectAlias }}
        objectAlias: {{ .objectAlias | quote }}
        {{- end }}
      {{- end }}
{{- end }}